### ISSUE TITLE
Update for LoE?

### ISSUE THREAD

**Issue by justinemerson** [corlettb/HDTAHPluginHAPlugin#4]
Plugin no longer works when an LoE card comes up on the drafting screen, and then breaks the whole draft.
Is there a way I can fix this myself?
Was very unhappy w/the Overwolf overlay so went back to this, but sadly it doesn't work anymore :( will you still be updating the plugin?

**Comment by jorismathijssen** [comment]
Trying to update it my self, not so much luck

**Comment by corlettb** [comment]
I've updated it for LoE
